### PR TITLE
Bump to 3.0.35, smithy regen

### PR DESCRIPTION
**Pull request by kwilcox**
http://docs.celeryproject.org/projects/kombu/en/latest/changelog.html#version-3-0-35

### CODE REVIEW

**Comment by jakirkham** [comment]
@kwilcox, it looks like you are using a older version of `conda-smithy`. As a result, the re-rendering here reverted the re-rendering that occurred in this PR ( https://github.com/conda-forge/kombu-feedstock/pull/1 ). Could you please update `conda-smithy` and re-render again to bring those changes back.

**Comment by kwilcox** [comment]
Oh boy, I can.  I'll look into some smithy changes that stores the version that was last run and to have regenerate make sure it isn't downgrading.

**Comment by jakirkham** [comment]
Should be 0.10.3, which I believe is still latest.

**Comment by jakirkham** [comment]
The versioning discussion with `conda-smithy` is tricky, but see this issue ( https://github.com/conda-forge/conda-smithy/issues/168 ). I agree that something like this would be nice, but it is tricky to do it in such a way that version itself doesn't cause a re-rendering PR. I suppose it can be argued about whether we mind this or not for an individual feedstock, but it does have some pretty serious ramifications for the overall system in terms of re-rendering PRs always being generated on update or being generated when there is a non-version relevant change.

**Pull request merged**
